//
//  HeartbeatSession.swift
//  heartbeats Watch App
//
//  Session model for heartbeat transmission
//

import Foundation

enum SessionStatus: String, Codable {
    case requested
    case accepted
    case active
    case completed
    case cancelled
}

struct HeartbeatSession: Codable, Identifiable {
    let id: String  // Auto-generated by Firebase
    var senderId: String
    var receiverId: String
    var status: SessionStatus
    var startedAt: Date
    var endedAt: Date?
    var ttl: Date  // Auto-delete timestamp
    var beats: [HeartbeatData]
    
    init(senderId: String, receiverId: String) {
        self.id = ""  // Will be set by Firebase
        self.senderId = senderId
        self.receiverId = receiverId
        self.status = .requested
        self.startedAt = Date()
        self.endedAt = nil
        self.ttl = Date().addingTimeInterval(60)  // 60 seconds TTL
        self.beats = []
    }
}
